// __typecheck.test-d.ts — compile-only check that the public barrel
// (index.d.ts) re-exports every symbol src/index.mjs re-exports at runtime.
// Not a runtime test; verified with `tsc --noEmit --strict` against this
// file. See the fix for the missing-router (and other modules) bug.

import {
  // core
  createContext,
  bind,
  markVar,
  flush,
  afterFlush,
  unbind,
  beginScope,
  endScope,
  dropScope,
  runScope,
  // boxes
  box,
  deepBox,
  shared,
  prop,
  // computed
  computed,
  // watch
  watch,
  watchEffect,
  // batch
  nextTick,
  batch,
  // dom
  component,
  fragment,
  refs,
  on,
  fromHTML,
  anchorBefore,
  anchorBeforeSplit,
  anchorAppend,
  normClass,
  setClass,
  normStyle,
  setStyle,
  // blocks
  ifBlock,
  ifChain,
  forBlock,
  mountChild,
  dynamicBlock,
  teleportBlock,
  slotBlock,
  slotContent,
  // for_diff
  createForState,
  seedForState,
  reconcile,
  extractKeys,
  longestIncreasingSubsequence,
  // store
  createStore,
  useStore,
  derivedStore,
  // router — the reported bug: these were missing from index.d.ts entirely
  createRouter,
  memoryHistory,
  historyAdapter,
  routerOutlet,
  routerLink,
  // async
  asyncComponent,
  mountAsyncChild,
  suspenseBlock,
  // lifecycle
  onMount,
  onDestroy,
  onUpdate,
  onActivated,
  onDeactivated,
  attach,
  isLive,
  // emits
  emit,
  registerEmits,
  eventPropName,
  // provide
  provide,
  inject,
  hasInjection,
  // transition
  withTransition,
  runPhase,
  // keepalive
  keepAlive,
} from "./index";

// Reference every import so an unused-import check can't hide a missing
// export (all of these are values, so this alone proves resolution).
void [
  createContext,
  bind,
  markVar,
  flush,
  afterFlush,
  unbind,
  beginScope,
  endScope,
  dropScope,
  runScope,
  box,
  deepBox,
  shared,
  prop,
  computed,
  watch,
  watchEffect,
  nextTick,
  batch,
  component,
  fragment,
  refs,
  on,
  fromHTML,
  anchorBefore,
  anchorBeforeSplit,
  anchorAppend,
  normClass,
  setClass,
  normStyle,
  setStyle,
  ifBlock,
  ifChain,
  forBlock,
  mountChild,
  dynamicBlock,
  teleportBlock,
  slotBlock,
  slotContent,
  createForState,
  seedForState,
  reconcile,
  extractKeys,
  longestIncreasingSubsequence,
  createStore,
  useStore,
  derivedStore,
  createRouter,
  memoryHistory,
  historyAdapter,
  routerOutlet,
  routerLink,
  asyncComponent,
  mountAsyncChild,
  suspenseBlock,
  onMount,
  onDestroy,
  onUpdate,
  onActivated,
  onDeactivated,
  attach,
  isLive,
  emit,
  registerEmits,
  eventPropName,
  provide,
  inject,
  hasInjection,
  withTransition,
  runPhase,
  keepAlive,
];
