//! Build script: generates one `#[test]` per sample case dir under
//! `tests/runtime/samples/`, so a failing case names itself and cases run in
//! parallel — without a proc-macro dependency. The generated file is
//! `include!`d by `tests/runtime_samples.rs`.
//!
//! A "case dir" is any directory under `tests/runtime/samples/` that contains
//! an `App.lunas`. Its test name is the path relative to `samples/` with
//! separators flattened (`text/interpolation` -> `case_text__interpolation`).
//!
//! Rerun triggers: the samples tree is walked and every relevant file is
//! emitted as a `cargo:rerun-if-changed`, so adding/removing a case or editing
//! a case file regenerates the manifest. The harness driver files are watched
//! too.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let samples = manifest_dir.join("tests/runtime/samples");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let generated = out_dir.join("runtime_samples_generated.rs");

    // Watch the samples tree and the harness driver so edits trigger a rebuild.
    println!("cargo:rerun-if-changed={}", samples.display());
    let harness = manifest_dir.join("tests/runtime/harness");
    println!("cargo:rerun-if-changed={}", harness.display());
    println!("cargo:rerun-if-env-changed=UPDATE_EXPECTED");

    let mut cases: Vec<String> = Vec::new();
    if samples.is_dir() {
        collect_cases(&samples, &samples, &mut cases);
    }
    cases.sort();

    let mut code = String::new();
    code.push_str("// @generated by build.rs — do not edit.\n");
    for rel in &cases {
        // Emit rerun triggers for each case's known files.
        let case_dir = samples.join(rel);
        for f in [
            "App.lunas",
            "_config.json",
            "expected.html",
            "steps.mjs",
            "expected.after.html",
        ] {
            let p = case_dir.join(f);
            if p.exists() {
                println!("cargo:rerun-if-changed={}", p.display());
            }
        }
        let fn_name = format!("case_{}", sanitize(rel));
        // Case names contain `__` (flattened `/`), which is not snake case;
        // allow it per-fn so `clippy -D warnings` stays green.
        writeln!(
            code,
            "#[test]\n#[allow(non_snake_case)]\nfn {fn_name}() {{ run_case({rel:?}); }}"
        )
        .unwrap();
    }

    std::fs::write(&generated, code).unwrap();
}

/// Recursively find directories containing an `App.lunas`, recording their path
/// relative to `root` (using `/` separators regardless of platform).
fn collect_cases(root: &Path, dir: &Path, out: &mut Vec<String>) {
    let entries = match std::fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    let mut has_app = false;
    let mut subdirs = Vec::new();
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            subdirs.push(path);
        } else if path.file_name().and_then(|n| n.to_str()) == Some("App.lunas") {
            has_app = true;
        }
    }
    if has_app {
        if let Ok(rel) = dir.strip_prefix(root) {
            let rel = rel.to_string_lossy().replace('\\', "/");
            out.push(rel);
        }
        // A case dir is a leaf for enumeration purposes; sibling `.lunas` files
        // belong to it. We still recurse in case of nested categories that also
        // hold direct cases, but that is an unusual layout.
    }
    for sub in subdirs {
        collect_cases(root, &sub, out);
    }
}

/// Turn a relative case path into a valid Rust identifier fragment.
fn sanitize(rel: &str) -> String {
    let mut s = String::new();
    let mut prev_sep = false;
    for ch in rel.chars() {
        if ch == '/' {
            s.push_str("__");
            prev_sep = true;
        } else if ch.is_ascii_alphanumeric() || ch == '_' {
            s.push(ch);
            prev_sep = false;
        } else {
            s.push('_');
            prev_sep = false;
        }
    }
    let _ = prev_sep;
    s
}
