name: Label PRs

on:
  pull_request:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Determine label and apply
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          if [[ "$BRANCH_NAME" == fix/* ]]; then
            LABEL="fix"
          elif [[ "$BRANCH_NAME" == feature/* ]]; then
            LABEL="feature"
          elif [[ "$BRANCH_NAME" == refactor/* ]]; then
            LABEL="refactor"
          elif [[ "$BRANCH_NAME" == version/* ]]; then
            LABEL="version"
          elif [[ "$BRANCH_NAME" == chore/* ]]; then
            LABEL="chore"
          else
            LABEL=""
          fi

          if [[ -n "$LABEL" ]]; then
            gh pr edit ${{ github.event.pull_request.number }} --add-label "$LABEL"
          fi
